### ISSUE TITLE
Wrappers for shell scripts

### ISSUE THREAD

**Issue by nicklambourne** [CoEDL/kaldi_helpers#34]
Python entry points for scripts currently written in bash

Alternatively, we could just port them to Python ;)

**Comment by fauxneticien** [comment]
> Alternatively, we could just port them to Python ;)

By all means, if it makes the whole package more harmonious and maintainable! There may have been ideas initially that bash was more lightweight than python for dependencies, but I see our kaldi-helpers image is in the gigabytes (with multiple python versions installed), so that's probably a non-issue now.

Since it's the entry point though, I hope whatever they're changed *to*, the user-facing docs are better than the current set up (hint through the use of [docopt](http://docopt.org/) or equivalent) 👍.
